language: python
nodejs: lts/*
python: 3.7
env:
  global:
  - AWS_DEFAULT_REGION=us-west-2
before_install:
- export PATH=$PATH:$HOME/.local/bin
# install:
# - pip install pipenv
# - pipenv install --dev
deploy:
- provider: script
  script: bash deploy/deploy.sh
  on:
    branch: master
    condition: $LAMBDA = test1
